
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 01 14:02:25 CST 2021
//----------------------------------------------------

package Syntactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int distinct = 22;
  public static final int piecename = 33;
  public static final int bracket_close = 8;
  public static final int end_if = 13;
  public static final int i_f = 10;
  public static final int giveup = 32;
  public static final int bracket_open = 7;
  public static final int higher = 17;
  public static final int semicolon = 16;
  public static final int moveto = 27;
  public static final int donothing = 31;
  public static final int EOF = 0;
  public static final int equal = 21;
  public static final int dot = 14;
  public static final int move = 26;
  public static final int posy = 24;
  public static final int less = 18;
  public static final int split = 6;
  public static final int posx = 23;
  public static final int movetoward = 28;
  public static final int quotes = 9;
  public static final int error = 1;
  public static final int integer = 2;
  public static final int moveawayfrom = 29;
  public static final int ehigher = 19;
  public static final int plus = 4;
  public static final int then = 12;
  public static final int per = 5;
  public static final int stats = 30;
  public static final int comma = 15;
  public static final int el_se = 11;
  public static final int erase = 3;
  public static final int eless = 20;
  public static final int name = 25;
}

